title: Tripureswari Marbles
author: yashLadha
email: panoramedia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tripureswari Marbles and Granites

twitter_username: macrod68
github_username:  macrod68

sass:
    style: compressed